---
- hosts: all
  become: yes
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      apt:
        name: python 
        update_cache: yes
  tasks: 
    - name: install php and stuff
      apt:
        name: php
        update_cache: yes
      